services:
  app:
    container_name: reply_guyz
    image: reply_guyz-app
    build: .
    environment:
      CHATGPT_SECRETKEY_PROJECT: ${CHATGPT_SECRETKEY_PROJECT}
      DATABASE: ${DATABASE}
      DB_HOST_DEV: ${DB_HOST_DEV}
      DB_PORT_DEV: ${DB_PORT_DEV}
      DB_PW: ${DB_PW}
      DB_USER: ${DB_USER}
      ENV: DEV # ENV | PROD
      PYTHONSTARTUP: ${PYTHONSTARTUP}
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - mysql
    restart: always

  mysql:
    container_name: mysql  
    build:
        context: .
        dockerfile: Dockerfile.mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PW}
      TZ: UTC  
    ports:
      - "127.0.0.1:3306:3306"  # Expose port for dev; remove for prod
    volumes:
      - .:/app  
      - mysql_data:/var/lib/mysql
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--local-infile=1",
      "--default-time-zone=+00:00"   
    ]
    restart: always

volumes:
  mysql_data:
